template: Get lost, %s!
defaultName: John

database:
  driverClass: com.mysql.jdbc.Driver
  user: flipkart
  password: flipkart
  url: jdbc:mysql://localhost/Library
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true

